FROM safe:latest
ARG GIT_SERVER

USER root

RUN apk add git
RUN apk add openssh
RUN apk add tk

USER safe

RUN mkdir /safe/instance/repositories

RUN mkdir /home/safe/.ssh
RUN ssh-keygen -t rsa -q -f "/home/safe/.ssh/id_rsa" -N ""
RUN ssh-keyscan $GIT_SERVER >> /home/safe/.ssh/known_hosts

ENTRYPOINT ["./boot-worker.sh"]
