FROM safe:latest
ARG GIT_SERVER

USER root

RUN apt-get -y install git
RUN apt-get -y install openssh-client
RUN apt-get -y install tk
RUN apt-get -y install build-essential

COPY worker-requirements.txt worker-requirements.txt
RUN venv/bin/pip install -r worker-requirements.txt

USER safe

RUN mkdir /safe/db
RUN mkdir /safe/instance/repositories

RUN mkdir /home/safe/.ssh
RUN ssh-keygen -t rsa -q -f "/home/safe/.ssh/id_rsa" -N ""
RUN ssh-keyscan $GIT_SERVER >> /home/safe/.ssh/known_hosts

ENTRYPOINT ["./boot-worker.sh"]
